name: demo_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  http: ^0.13.4
  cupertino_icons: ^1.0.0
  rxdart: ^0.27.5
  loading_indicator: ^3.1.0
  gradient_borders: ^1.0.0
  path_provider: ^2.0.10
  responsive_framework: ^0.2.0

  #  image and file picker
  file_picker: ^5.2.5
  image_picker: ^0.8.6

  #  Social Login
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^4.4.0+1
  crypto: ^3.0.2

  #  Database
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.14

  #  Firebase
  flutter_local_notifications: ^13.0.0
  cloud_firestore: ^4.0.4
  firebase_database: ^10.0.4
  firebase_messaging: ^14.2.5
  firebase_auth: ^4.1.1
  firebase_storage: ^11.0.14

  #  Ad
  facebook_audience_network: ^1.0.1
  google_mobile_ads: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Language/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800

