name: demo_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  http: ^0.13.4
  sqflite: ^2.0.2+1
  sizer: ^2.0.15
  path_provider: ^2.0.10
  shared_preferences: ^2.0.14
  geolocator: ^8.2.1
  location: ^4.4.0
  permission_handler: ^9.2.0
  syncfusion_flutter_gauges: ^20.1.57
  cupertino_icons: ^1.0.0
  firebase_database: ^10.0.4
  cloud_firestore: ^4.0.4
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^13.0.0
  rxdart: ^0.27.5
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^4.4.0+1
  edge_detection: ^1.0.4
  firebase_auth: ^4.1.1
  loading_indicator: ^3.1.0
  flutter_masked_text2: ^0.9.1
  file_picker: ^5.2.5
  image_picker: ^0.8.6
  crypto: ^3.0.2
  gradient_borders: ^1.0.0
  firebase_storage: ^11.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_speedometer:
#    path: ./Package/Flutter-Speedometer-master

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Language/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
